#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: pyproject
# autospec version: v18
# autospec commit: f35655a
#
Name     : pypi-jupyterlite_pyodide_kernel
Version  : 0.4.1
Release  : 1
URL      : https://files.pythonhosted.org/packages/14/b5/3d20c507091036ed828cc1754ee86baf0645ab63bb5a0c589511866b00e5/jupyterlite_pyodide_kernel-0.4.1.tar.gz
Source0  : https://files.pythonhosted.org/packages/14/b5/3d20c507091036ed828cc1754ee86baf0645ab63bb5a0c589511866b00e5/jupyterlite_pyodide_kernel-0.4.1.tar.gz
Summary  : Python kernel for JupyterLite powered by Pyodide
Group    : Development/Tools
License  : BSD-3-Clause
Requires: pypi-jupyterlite_pyodide_kernel-bin = %{version}-%{release}
Requires: pypi-jupyterlite_pyodide_kernel-data = %{version}-%{release}
Requires: pypi-jupyterlite_pyodide_kernel-python = %{version}-%{release}
Requires: pypi-jupyterlite_pyodide_kernel-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pypi(hatchling)
BuildRequires : pypi(jupyterlab)
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
# jupyterlite-pyodide-kernel
> A Python kernel for [JupyterLite](https://jupyterlite.rtfd.io) powered by
> [Pyodide](https://pyodide.org),

%package bin
Summary: bin components for the pypi-jupyterlite_pyodide_kernel package.
Group: Binaries
Requires: pypi-jupyterlite_pyodide_kernel-data = %{version}-%{release}

%description bin
bin components for the pypi-jupyterlite_pyodide_kernel package.


%package data
Summary: data components for the pypi-jupyterlite_pyodide_kernel package.
Group: Data

%description data
data components for the pypi-jupyterlite_pyodide_kernel package.


%package python
Summary: python components for the pypi-jupyterlite_pyodide_kernel package.
Group: Default
Requires: pypi-jupyterlite_pyodide_kernel-python3 = %{version}-%{release}

%description python
python components for the pypi-jupyterlite_pyodide_kernel package.


%package python3
Summary: python3 components for the pypi-jupyterlite_pyodide_kernel package.
Group: Default
Requires: python3-core
Provides: pypi(jupyterlite_pyodide_kernel)
Requires: pypi(jupyterlite_core)
Requires: pypi(pkginfo)

%description python3
python3 components for the pypi-jupyterlite_pyodide_kernel package.


%prep
%setup -q -n jupyterlite_pyodide_kernel-0.4.1
cd %{_builddir}/jupyterlite_pyodide_kernel-0.4.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1723561855
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export MAKEFLAGS=%{?_smp_mflags}
python3 -m build --wheel --skip-dependency-check --no-isolation

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
python3 -m installer --destdir=%{buildroot} dist/*.whl
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/jupyter-piplite

%files data
%defattr(-,root,root,-)
/usr/share/jupyter/labextensions/@jupyterlite/pyodide-kernel-extension/install.json
/usr/share/jupyter/labextensions/@jupyterlite/pyodide-kernel-extension/package.json
/usr/share/jupyter/labextensions/@jupyterlite/pyodide-kernel-extension/static/154.b84bb3de4c12e59b569c.js
/usr/share/jupyter/labextensions/@jupyterlite/pyodide-kernel-extension/static/154.b84bb3de4c12e59b569c.js.map
/usr/share/jupyter/labextensions/@jupyterlite/pyodide-kernel-extension/static/248.e5013c38fd241ed9d509.js
/usr/share/jupyter/labextensions/@jupyterlite/pyodide-kernel-extension/static/248.e5013c38fd241ed9d509.js.LICENSE.txt
/usr/share/jupyter/labextensions/@jupyterlite/pyodide-kernel-extension/static/248.e5013c38fd241ed9d509.js.map
/usr/share/jupyter/labextensions/@jupyterlite/pyodide-kernel-extension/static/304.0bb9abc93cc92244ff25.js
/usr/share/jupyter/labextensions/@jupyterlite/pyodide-kernel-extension/static/304.0bb9abc93cc92244ff25.js.LICENSE.txt
/usr/share/jupyter/labextensions/@jupyterlite/pyodide-kernel-extension/static/304.0bb9abc93cc92244ff25.js.map
/usr/share/jupyter/labextensions/@jupyterlite/pyodide-kernel-extension/static/352.82066d1c2366a6f42104.js
/usr/share/jupyter/labextensions/@jupyterlite/pyodide-kernel-extension/static/352.82066d1c2366a6f42104.js.LICENSE.txt
/usr/share/jupyter/labextensions/@jupyterlite/pyodide-kernel-extension/static/352.82066d1c2366a6f42104.js.map
/usr/share/jupyter/labextensions/@jupyterlite/pyodide-kernel-extension/static/620.5d1ded170db5d0c1f7b2.js
/usr/share/jupyter/labextensions/@jupyterlite/pyodide-kernel-extension/static/620.5d1ded170db5d0c1f7b2.js.LICENSE.txt
/usr/share/jupyter/labextensions/@jupyterlite/pyodide-kernel-extension/static/620.5d1ded170db5d0c1f7b2.js.map
/usr/share/jupyter/labextensions/@jupyterlite/pyodide-kernel-extension/static/pypi/all.json
/usr/share/jupyter/labextensions/@jupyterlite/pyodide-kernel-extension/static/pypi/ipykernel-6.9.2-py3-none-any.whl
/usr/share/jupyter/labextensions/@jupyterlite/pyodide-kernel-extension/static/pypi/piplite-0.4.1-py3-none-any.whl
/usr/share/jupyter/labextensions/@jupyterlite/pyodide-kernel-extension/static/pypi/pyodide_kernel-0.4.1-py3-none-any.whl
/usr/share/jupyter/labextensions/@jupyterlite/pyodide-kernel-extension/static/pypi/widgetsnbextension-3.6.6-py3-none-any.whl
/usr/share/jupyter/labextensions/@jupyterlite/pyodide-kernel-extension/static/pypi/widgetsnbextension-4.0.11-py3-none-any.whl
/usr/share/jupyter/labextensions/@jupyterlite/pyodide-kernel-extension/static/remoteEntry.e96be077d96e844d0c72.js
/usr/share/jupyter/labextensions/@jupyterlite/pyodide-kernel-extension/static/remoteEntry.e96be077d96e844d0c72.js.map
/usr/share/jupyter/labextensions/@jupyterlite/pyodide-kernel-extension/static/schema/kernel.v0.schema.json
/usr/share/jupyter/labextensions/@jupyterlite/pyodide-kernel-extension/static/schema/piplite.v0.schema.json
/usr/share/jupyter/labextensions/@jupyterlite/pyodide-kernel-extension/static/style.js
/usr/share/jupyter/labextensions/@jupyterlite/pyodide-kernel-extension/static/third-party-licenses.json

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
